[package]
name = "pallet-hotfix"
authors = { workspace = true }
edition = "2021"
version = "0.1.0"

[dependencies]
# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true, features = [ "derive" ] }
sp-core = { workspace = true }
sp-std = { workspace = true }
# Frontier
pallet-evm = { workspace = true, features = ["forbid-evm-reentrancy"] }

# Benchmarks
frame-benchmarking = { workspace = true, optional = true }

[dev-dependencies]
sp-runtime = { workspace = true, features = ["std"] }
sp-io = { workspace = true, features = [ "std" ] }
pallet-balances = { workspace = true, features = [ "std" ] }
pallet-timestamp = { workspace = true, features = [ "std" ] }
rlp = { workspace = true, features = [ "std" ] }
libsecp256k1 = { workspace = true, features = [ "std" ] }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "frame-system/std",
    "frame-benchmarking/std",
    "parity-scale-codec/std",
    "scale-info/std",
    "sp-core/std",
    "sp-std/std",
    "sp-runtime/std",
    "sp-io/std",
    "pallet-evm/std",
    "pallet-balances/std",
    "pallet-timestamp/std",
    "rlp/std",
    "libsecp256k1/std",
]

runtime-benchmarks = [
    "frame-benchmarking",
]